<?php
/**
 * Copyright © 2024. Techstacks Ph All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block ListingFee */

use Techstacks\Legacy\Block\Adminhtml\ListingFee\ListingFee;

?>

<div class="admin__data-grid-wrap" data-role="sticky-el-root">
    <table class="data-grid" style="width: 100%; transform: translate(0px, 0px);">
        <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Seller ID'">Seller ID</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Name'">Name</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Email'">Email</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Store Title'">Store Title</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Total Active Products'">Total Active Products</span>
                </th>
                <!-- headers for number of total payable -->
                <!-- headers for create invoice action -->
            </tr>
        </thead>
        <tbody>
        <?php
        $sellers = $block->getSellersCollection()->getItems();
        foreach ($sellers as $seller) {
            if ($seller->getData('is_vendor')) { ?>
                <tr class="data-row">
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('user_id'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('name'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('email'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('storetitle'); ?>
                        </div>
                    </td>

                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $block->getProductsCollection($seller->getData('user_id')); ?>
                        </div>
                    </td>
                    <!-- table data for number of active products -->
                    <!-- table data for number of total payable -->
                    <!-- table data for create invoice action -->
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
</div>
