<?php
/**
 * Copyright © 2024. Techstacks Ph All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block Listing */

use Techstacks\Legacy\Block\Adminhtml\Listing\Listing;

?>

<div class="admin__data-grid-wrap" data-role="sticky-el-root">
    <table class="data-grid" style="width: 100%; transform: translate(0px, 0px);">
        <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Seller ID'">Seller ID</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Name'">Name</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Email'">Email</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Store Title'">Store Title</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Total Active Products'">Total Active Products</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Total Listing Fee'">Total Listing Fee</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" data-bind="i18n: 'Action'">Action</span>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php
        $sellers = $block->getSellersCollection()->getItems();
        foreach ($sellers as $seller) {
            if ($seller->getData('is_vendor')) { ?>
                <tr class="data-row">
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('user_id'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('name'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('email'); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $seller->getData('storetitle'); ?>
                        </div>
                    </td>

                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $block->getTotalActiveProductsBySellerId($seller->getData('user_id')); ?>
                        </div>
                    </td>

                    <td>
                        <div class="data-grid-cell-content">
                            <?php echo $block->getTotalListingFeeBySellerId($seller->getData('user_id')); ?>
                        </div>
                    </td>

                    <td>
                        <div class="data-grid-cell-content">
                            <button>
                                Create Invoice
                            </button>
                        </div>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
</div>
