<?php
/**
 * Copyright © 2024. Techstacks Ph All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block ListingFee */

use Techstacks\Legacy\Block\Adminhtml\ListingFee\ListingFee;

?>

<p>Sellers List</p>

<?php

$customers = $block->getSellersCollection()->getItems();
foreach ($customers as $customer) {
    if($customer->getData('is_vendor')) {
        echo $customer->getData('name');
    }
}
